# Generated by Django 4.0.4 on 2022-07-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
