# Generated by Django 4.0.4 on 2022-08-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
