# Generated by Django 4.0.4 on 2022-06-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='img',
        ),
    ]
