# Generated by Django 4.0.4 on 2022-06-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_publicacion_options_remove_publicacion_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
