# Generated by Django 4.0.4 on 2022-06-27 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_publicacion_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='image',
            new_name='imagen',
        ),
    ]
