# Generated by Django 4.0.4 on 2022-06-27 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rename_image_publicacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen',
        ),
    ]
