# Generated by Django 4.0.4 on 2022-06-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_publicacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='home'),
        ),
    ]
