# Generated by Django 4.0.4 on 2022-06-07 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_remove_producto_category_producto_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
