# Generated by Django 4.0.4 on 2022-06-07 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='image',
            new_name='imagen',
        ),
    ]
