# Generated by Django 4.0.4 on 2022-06-27 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0010_rename_image_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
