# Generated by Django 4.0.4 on 2022-06-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0011_remove_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='', upload_to='productos'),
            preserve_default=False,
        ),
    ]
